### ISSUE TITLE
Jupyter console autocompletion gives bad suggestions

### ISSUE THREAD

**Issue by fredcallaway** [evhub/coconut#114]
The main benefit of the Jupyter console for me is the autocompletion, but it is buggy for coconut. It suggests attributes that the object doesn't actually have.

```
In [7]: foo.   # TAB
foo.MatchError             foo._coconut_map           foo.foo
foo.__builtins__           foo._coconut_minus         foo.generator_stop
foo.__name__               foo._coconut_parallel_map  foo.map   # <== LOOK HERE
foo._coconut               foo._coconut_pipe          foo.parallel_map
foo._coconut_MatchError    foo._coconut_starpipe      foo.prepattern
foo._coconut_backpipe      foo._coconut_sys           foo.y3_map
foo._coconut_backstarpipe  foo._coconut_zip           foo.y3_zip
foo._coconut_bool_and      foo.addpattern             foo.recursive
foo._coconut_bool_or       foo.consume                foo.reduce
foo._coconut_compose       foo.count                  foo.takewhile
foo._coconut_count         foo.datamaker              foo.tee
foo._coconut_igetitem      foo.dropwhile              foo.zip

In [7]: foo.map
Traceback (most recent call last):
  File "/Users/fred/anaconda/lib/python3.5/site-packages/coconut/command.py", line 164, in run
    exec(code, self.vars)
  File "<string>", line 1, in <module>
AttributeError: 'list' object has no attribute 'map'
```

Also, perhaps the  `_coconut` attributes should be hidden. I'm not sure if that's possible.

**Comment by evhub** [comment]
Ah, I see the problem. Coconut is suggesting variables instead of attributes. And you're right, I should get rid of the `_coconut` names.

**Comment by evhub** [comment]
Fixed in develop! Will be included in the next release.
