### ISSUE TITLE
Pickle fails in REPL

### ISSUE THREAD

**Issue by Boscillator** [evhub/coconut#146]
This is a bit of a nitpick, but in the interest of total python compatibility:

When the following code is run in the coconut interpreter it fails:
```
import pickle

class C(object): pass

myC = C()

print(pickle.dumps(myC))
```
with
```
>>> print(pickle.dumps(myC))
Traceback (most recent call last):
  File "c:\users\oscil\documents\coconut\coconut\coconut\command\utils.py", line 106, in run
    return run_func(code, self.vars)
  File "c:\users\oscil\documents\coconut\coconut\coconut\command\utils.py", line 68, in try_eval
    return eval(code, in_vars)
  File "<string>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class '__main__.C'>: attribute lookup C on __main__ failed
```
In the python interpreter, it yields the following, as is should:
```
>>> print(pickle.dumps(myC))
b'\x80\x03c__main__\nC\nq\x00)\x81q\x01.'
```
However when compiled with coconut it works. 

I think this has something to do with the main module not being registered correctly for pickle to work.

**Comment by evhub** [comment]
The solution for this is #73. I've been aware of this issue for a while, but it turns out that fixing it is a lot more difficult than you would think. Currently, I do a special hack to make sure that all the built-ins are pickleable (and thus can be used with `parallel_map`), but if you define something manually, it still isn't.

**Comment by evhub** [comment]
Also duplicates #31, which itself duplicates #73. I think I'm just going to consolidate everything into this issue.
