### ISSUE TITLE
Infix Notation Example broken

### ISSUE THREAD

**Issue by mattjegan** [evhub/coconut#278]
I've recently discovered Coconut and began playing with it by going down the [homepage](http://coconut-lang.org/) and found that the "infix notation" example didn't run on my system in the coconut interpreter using python3.5.1. The output is as follows:
```python3
>>> 5 `mod` 3 == 2
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/coconut/command/util.py", line 365, in handling_errors
    yield
  File "/venv/lib/python3.5/site-packages/coconut/command/util.py", line 387, in run
    result = run_func(code, self.vars)
  File "/venv/lib/python3.5/site-packages/coconut/command/util.py", line 140, in interpret
    result = eval(code, in_vars)
  File "<string>", line 1, in <module>
NameError: name 'mod' is not defined

>>> 5 mod 3 == 2
    
CoconutParseError: parsing failed (line 1)
  5 mod 3 == 2

>>> 5 'mod' 3 == 2
    
CoconutParseError: parsing failed (line 1)
  5 'mod' 3 == 2
```
Let me know if I've missed any crucial info

**Comment by mattjegan** [comment]
Ahh apologies, I've just realised that `mod` may actually be an imported function, can someone clarify this was the correct intent before I close the issue?

**Comment by mattjegan** [comment]
Thanks @evhub for clearing that up for me
