### ISSUE TITLE
Coconut emits error 10093 in Cygwin bash

### ISSUE THREAD

**Issue by halloleo** [evhub/coconut#295]
On Windows, on top of a vanilla Python 2.7 install, coconut does not play nicely when started from Cygwin bash: 

    $ coconut -r -l factorial.coco
    Coconut: Compiling         factorial.coco ...
    Coconut: Compiled to       factorial.py .
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\coconut\command\command.py", line 259, in handling_exceptions
        yield
      File "c:\python27\lib\site-packages\coconut\command\command.py", line 113, in cmd
        self.use_args(args, interact)
      File "c:\python27\lib\site-packages\coconut\command\command.py", line 225, in use_args
        if stdin_readable():
      File "c:\python27\lib\site-packages\coconut\command\util.py", line 249, in stdin_readable
        return bool(select([sys.stdin], [], [], 0)[0])
    error: (10093, 'Either the application has not called WSAStartup, or WSAStartup failed')
    Coconut: Exiting due to error.

So it does the compiling perfectly (it even does run the code via `-r` properly) just while returning to the command line the hiccup occurs.

**Comment by evhub** [comment]
@halloleo Thanks for the bug report! I think this has been fixed on `develop`. Try `pip install coconut-develop` and test it out!

**Comment by halloleo** [comment]
@evhub Cool! Very prompt fix. I've tested it and it works. Thanks.
