### ISSUE TITLE
enablePackrat() error

### ISSUE THREAD

**Issue by ArneBachmann** [evhub/coconut#311]
Any ideas? Could be that my system is in a bad state regarding Py2/Py3 installation locations (mixed pip store).
```ash@mega:~/Desktop/svn> /usr/bin/coconut
Traceback (most recent call last):
  File "/usr/bin/coconut", line 7, in <module>
    from coconut.main import main
  File "/usr/lib/python3.4/site-packages/coconut/main.py", line 35, in <module>
    from coconut.command import Command
  File "/usr/lib/python3.4/site-packages/coconut/command/__init__.py", line 20, in <module>
    from coconut.command.command import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/command/command.py", line 30, in <module>
    from coconut.compiler import Compiler
  File "/usr/lib/python3.4/site-packages/coconut/compiler/__init__.py", line 20, in <module>
    from coconut.compiler.compiler import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/compiler/compiler.py", line 89, in <module>
    from coconut.compiler.grammar import (
  File "/usr/lib/python3.4/site-packages/coconut/compiler/grammar.py", line 97, in <module>
    ParserElement.enablePackrat(packrat_cache_size)
TypeError: enablePackrat() takes 0 positional arguments but 1 was given
```

**Comment by evhub** [comment]
@ArneBachmann This error occurs if you are running an outdated version of `pyparsing`. Coconut v1.2.3 (the current version) requires `pyparsing==2.2.0`. When you run `pip install coconut`, if you have a proper installation of `pip`, it should update your `pyparsing` automatically, but it looks like for you it didn't for some reason. There is no way for me to fix this, since Coconut is already doing everything it can to tell `pip` that it depends on `pyparsing==2.2.0`, but I have made this error nicer in `coconut-develop`, which will at some point become the next release.

**Comment by evhub** [comment]
This error is resolved by running `pip install pyparsing`, and with the v1.3.0 release, Coconut will now tell you to do that explicitly.

**Comment by ArneBachmann** [comment]
No idea why it's not working, but it might be my system being messed up.
```
ash@mega:~/Desktop/svn/projects/scripts> pip3 install "pyparsing==2.2.0"
Requirement already satisfied (use --upgrade to upgrade): pyparsing==2.2.0 in /usr/lib/python3.4/site-packages
ash@mega:~/Desktop/svn/projects/scripts> pip3 install pyparsing
Requirement already satisfied (use --upgrade to upgrade): pyparsing in /usr/lib/python3.4/site-packages
ash@mega:~/Desktop/svn/projects/scripts> coconut
Traceback (most recent call last):
  File "/usr/bin/coconut", line 7, in <module>
    from coconut.main import main
  File "/usr/lib/python3.4/site-packages/coconut/main.py", line 35, in <module>
    from coconut.command import Command
  File "/usr/lib/python3.4/site-packages/coconut/command/__init__.py", line 20, in <module>
    from coconut.command.command import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/command/command.py", line 30, in <module>
    from coconut.compiler import Compiler
  File "/usr/lib/python3.4/site-packages/coconut/compiler/__init__.py", line 20, in <module>
    from coconut.compiler.compiler import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/compiler/compiler.py", line 89, in <module>
    from coconut.compiler.grammar import (
  File "/usr/lib/python3.4/site-packages/coconut/compiler/grammar.py", line 97, in <module>
    ParserElement.enablePackrat(packrat_cache_size)
TypeError: enablePackrat() takes 0 positional arguments but 1 was given
```

**Comment by evhub** [comment]
@ArneBachmann Are you sure Coconut is installed under the same Python installation as `pip3`? Try this:
```
python3 -m pip install --upgrade pyparsing coconut
python3 -m coconut
```

**Comment by ArneBachmann** [comment]
```
ash@mega:~/.ethereum> python3 -m pip install --upgrade pyparsing coconut
Requirement already up-to-date: pyparsing in /usr/lib/python3.4/site-packages
Requirement already up-to-date: coconut in /usr/lib/python3.4/site-packages
Requirement already up-to-date: prompt-toolkit>=1.0 in /usr/lib/python3.4/site-packages (from coconut)
Requirement already up-to-date: pygments>=2.2 in /usr/lib64/python3.4/site-packages (from coconut)
Requirement already up-to-date: wcwidth in /usr/lib/python3.4/site-packages (from prompt-toolkit>=1.0->coconut)
Requirement already up-to-date: six>=1.9.0 in /usr/lib/python3.4/site-packages (from prompt-toolkit>=1.0->coconut)
ash@mega:~/.ethereum> coconut
Traceback (most recent call last):
  File "/usr/bin/coconut", line 7, in <module>
    from coconut.main import main
  File "/usr/lib/python3.4/site-packages/coconut/main.py", line 35, in <module>
    from coconut.command import Command
  File "/usr/lib/python3.4/site-packages/coconut/command/__init__.py", line 20, in <module>
    from coconut.command.command import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/command/command.py", line 30, in <module>
    from coconut.compiler import Compiler
  File "/usr/lib/python3.4/site-packages/coconut/compiler/__init__.py", line 20, in <module>
    from coconut.compiler.compiler import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/compiler/compiler.py", line 89, in <module>
    from coconut.compiler.grammar import (
  File "/usr/lib/python3.4/site-packages/coconut/compiler/grammar.py", line 97, in <module>
    ParserElement.enablePackrat(packrat_cache_size)
TypeError: enablePackrat() takes 0 positional arguments but 1 was given
```

**Comment by evhub** [comment]
@ArneBachmann Try `python3 -m coconut`, not `coconut`, to make sure you're using the right version of Coconut. Also, what happens when you do `coconut -v`?

**Comment by ArneBachmann** [comment]
I found the solution:
- First I had to explicitly update coconut via `sudo pip3 install "coconut==1.3.0"`, because `pip install coconut` will not pick the latest version, but the cached version 1.2.3
- I had to manually install `cytho`n and `cpyparsing` using `pip`; both have a setup.py that seems to use a (C-) compiler in the background (?) and took a while of 100% CPU to finish; might be an issue on Windows, but I didn't test
Afterwards, coconut started up fine!

So the problem seems to stem from a dependency on cPyparsing, which is not automatically installed.

**Comment by evhub** [comment]
@ArneBachmann It makes sense that that would work, though Coconut definitely doesn't depend on `cPyparsing`; it depends on `pyparsing`, but will use `cPyparsing` if available. Thus, if there's a problem with your `pyparsing` installation (like in this case), using `cPyparsing` instead would fix that problem. Glad to here Coconut is working for you now!
