### ISSUE TITLE
Coconut 1.3.0 from pypi crashing on python 3.4.6 with KeyError "magicfuncs"

### ISSUE THREAD

**Issue by mftrhu** [evhub/coconut#329]
I installed coconut 1.3.0 from pypi via pip and tried to run it with python 3.4.6. It crashes with `KeyError` on any command, included `--version`. It runs fine otherwise when installed and running under python 2.7.13.

Traceback:
```
Traceback (most recent call last):
  File "/usr/bin/coconut", line 7, in <module>
    from coconut.main import main
  File "/usr/lib/python3.4/site-packages/coconut/main.py", line 35, in <module>
    from coconut.command import Command
  File "/usr/lib/python3.4/site-packages/coconut/command/__init__.py", line 20, in <module>
    from coconut.command.command import *  # NOQA
  File "/usr/lib/python3.4/site-packages/coconut/command/command.py", line 51, in <module>
    from coconut.command.util import (
  File "/usr/lib/python3.4/site-packages/coconut/command/util.py", line 43, in <module>
    from coconut.highlighter import CoconutLexer
  File "/usr/lib/python3.4/site-packages/coconut/highlighter.py", line 74, in <module>
    class CoconutLexer(Python3Lexer):
  File "/usr/lib/python3.4/site-packages/coconut/highlighter.py", line 99, in CoconutLexer
    tokens["magicfuncs"] += [
KeyError: 'magicfuncs'
```

**Comment by evhub** [comment]
@mftrhu Somehow you're running an outdated version of `pygments`. You should be able to `pip install --upgrade pygments` to fix the issue.

**Comment by mftrhu** [comment]
~~That's what I thought too, but I already tried upgrading `pygments` yesterday _and_ today, with `pip` telling me that `Requirement already up-to-date: pygments in /usr/lib/python3.4/site-packages`.~~

~~`pip3 freeze | grep Pygments` tells me that I have `Pygments==2.2.0` installed, which is the same version that I apparently have on python 2~~

I'm a dolt and didn't check whether Pygments was also installed by my distro's package manager. For some reason it was (v.2.0.2) and it was also overriding the version I installed via pip. This issue can be closed.

**Comment by evhub** [comment]
@mftrhu Great, glad to hear it's working! There's not much I can do to change Coconut to make it better at handling errors like these, since it already tells `pip` it depends on `pygments>=2.2.0`, though I have added a more informative error message for this to `coconut-develop`.
