### ISSUE TITLE
Error for IPython/Jupyter Support

### ISSUE THREAD

**Issue by GeneralEbisu** [evhub/coconut#340]
I'm trying to use Coconut in Spyder IDE. 

But before that I have to launch an IPython/Jupyter console using Coconut as the kernel, right?

Anyways heres the error:

(C:\Users\cedri\Anaconda3) C:\Users\cedri>coconut --ipython console
Coconut: Successfully installed Coconut Jupyter kernel.
Traceback (most recent call last):
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\command.py", line 268, in handling_exceptions
    yield
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\command.py", line 118, in cmd
    self.use_args(parsed_args, interact, original_args=args)
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\command.py", line 239, in use_args
    self.start_jupyter(args.jupyter)
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\command.py", line 621, in start_jupyter
    install_func(["python" + ver, "-m", "coconut.main", "--version"])
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\util.py", line 242, in run_cmd
    stdout, stderr, _ = call_output(cmd, **kwargs)
  File "C:\Users\cedri\Anaconda3\lib\site-packages\coconut\command\util.py", line 211, in call_output
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "C:\Users\cedri\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\cedri\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
(you should report this at https://github.com/evhub/coconut/issues/new)
Coconut: Exiting due to FileNotFoundError.

**Comment by evhub** [comment]
@GeneralEbisu I believe this is the same error as #337, so it should work if you just `pip install coconut-develop`.

**Comment by evhub** [comment]
As for how to use Spyder, syntax highlighting should be automatic since Spyder uses Pygments, and you should be able to either `%load_ext coconut` into the automatic kernel, or select "load an existing kernel" from the settings and enter the information you get when you type `%connect_info` into a `coconut --jupyter console`.
