### ISSUE TITLE
Anaconda installation Failure While Trying To build Pytorch...

### ISSUE THREAD

**Issue by AdityaSoni19031997** [evhub/coconut#358]
While i am trying to build Pytorch i am not able to do so..
```
(C:\ProgramData\Anaconda3) C:\Users\adity\Desktop\pytorch-0.2.1-py36he6bf560_0.2.1cu80\info>conda-build recipe\
BUILD START: ['pytorch-0.2.1-py36he6bf560_0.2.1cu80.tar.bz2']

The following NEW packages will be INSTALLED:

    cffi:           1.10.0-py36hae3d1b5_1
    mkl:            2017.0.3-0
    numpy:          1.11.3-py36_0
    pip:            9.0.1-py36h226ae91_4
    pycparser:      2.18-py36hd053e01_1
    python:         3.6.2-h09676a0_15
    pyyaml:         3.12-py36h1d1928f_1
    setuptools:     27.2.0-py36_1
    vc:             14-h2379b0c_2
    vs2015_runtime: 14.0.25420-0
    wheel:          0.29.0-py36h6ce6cde_1
    yaml:           0.1.7-vc14hb31d195_1

Copying D:\Projects\pytorch to C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work
source tree in: C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work
Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.
WARNING:conda_build.windows:Using legacy MSVC compiler setup.  This will be removed in conda-build 4.0. If this recipe does not use a compiler, this message is safe to ignore.  Otherwise, use {{compiler('<language>')}} jinja2 in requirements/build.

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_BUILD=1"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PYTHONNOUSERSITE=1"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_DEFAULT_ENV=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ARCH=64"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PREFIX=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "BUILD_PREFIX=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SYS_PREFIX=C:\ProgramData\Anaconda3"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SYS_PYTHON=C:\ProgramData\Anaconda3\python.exe"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SUBDIR=win-64"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SRC_DIR=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ROOT=C:\ProgramData\Anaconda3"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_PY=36"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PY3K=1"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PY_VER=3.6"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "STDLIB_DIR=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SP_DIR=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PYTHON=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\python.exe"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "NPY_VER=1.11"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_NPY=1.11"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PERL_VER=5.22"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_PERL=5.22.2"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LUA_VER=5"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_LUA=5"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "R_VER=3"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_R=3"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PKG_NAME=pytorch"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PKG_VERSION=0.2.1"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PKG_BUILDNUM=0"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PKG_BUILD_STRING=py36he6bf560_0.2.1cu80"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PKG_HASH=h2fd56af"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "RECIPE_DIR=C:\Users\adity\Desktop\pytorch-0.2.1-py36he6bf560_0.2.1cu80\info\recipe"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CPU_COUNT=4"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SHLIB_EXT=.dll"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PATH=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\usr\bin;;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\bin;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Scripts;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Scripts;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\usr\bin;;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\bin;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Scripts;C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Scripts;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\TDM-GCC-64\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\TDM-GCC-64\x86_64-w64-mingw32\bin;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin;C:\Users\adity\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\adity\AppData\Local\Programs\Python\Python36-32\;C:\Users\adity\AppData\Local\Microsoft\WindowsApps;"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SCRIPTS=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Scripts"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LIBRARY_PREFIX=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LIBRARY_BIN=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\bin"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LIBRARY_INC=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\include"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LIBRARY_LIB=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\lib"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CYGWIN_PREFIX=/cygdrive/c/ProgramData/Anaconda3/conda-bld/pytorch_1510034197347/_h_env"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ALLUSERSPROFILE=C:\ProgramData"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "APPDATA=C:\Users\adity\AppData\Roaming"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CommonProgramFiles=C:\Program Files\Common Files"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CommonProgramW6432=C:\Program Files\Common Files"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "COMPUTERNAME=DESKTOP-V3IQLHT"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ComSpec=C:\Windows\system32\cmd.exe"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "HOMEDRIVE=C:"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "HOMEPATH=\Users\adity"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LOCALAPPDATA=C:\Users\adity\AppData\Local"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LOGONSERVER=\\DESKTOP-V3IQLHT"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "NUMBER_OF_PROCESSORS=4"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ProgramData=C:\ProgramData"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ProgramFiles=C:\Program Files"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ProgramFiles(x86)=C:\Program Files (x86)"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "ProgramW6432=C:\Program Files"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PROMPT=(C:\ProgramData\Anaconda3) $P$G"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PUBLIC=C:\Users\Public"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SystemDrive=C:"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "SystemRoot=C:\Windows"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "TEMP=C:\Users\adity\AppData\Local\Temp"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "TMP=C:\Users\adity\AppData\Local\Temp"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "USERDOMAIN=DESKTOP-V3IQLHT"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "USERNAME=aditya"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "USERPROFILE=C:\Users\adity"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "windir=C:\Windows"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PROCESSOR_ARCHITECTURE=AMD64"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "BUILD=amd64-pc-windows-19.0.0"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "r_base=3"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "cpu_optimization_target=nocona"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "target_platform=win-64"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "pin_run_as_build={'python': {'max_pin': 'x.x', 'min_pin': 'x.x'}}"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CONDA_BUILD_STATE=BUILD"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set DISTUTILS_USE_SDK=1

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set MSSdk=1

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set PY_VCRUNTIME_REDIST=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\bin\vcruntime140.dll

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "VS_VERSION=14.0"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "VS_MAJOR=14"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "VS_YEAR=2015"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "CMAKE_GENERATOR=Visual Studio 14 2015 Win64"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "MSYS2_ARG_CONV_EXCL=/AI;/AL;/OUT;/out"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "MSYS2_ENV_CONV_EXCL=CL"

**(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
Setting environment for using Microsoft Visual Studio 2010 x64 tools.
The system cannot find the path specified.
ERROR: Cannot determine the location of the VS installation.**

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "INCLUDE=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\include;"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set "LIB=C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\lib;"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>call "C:\ProgramData\Anaconda3\Scripts\activate.bat" "C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env"

(C:\ProgramData\Anaconda3) C:\ProgramData\Anaconda3\etc\conda\deactivate.d>set KERAS_BACKEND=

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>REM ===== end generated header =====

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>REM copy C:\Anaconda2\Lib\distutils\distutils.cfg C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Library\lib\distutils

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>REM set NO_CUDA=1

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>set NO_DISTRIBUTED=1

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>"C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\python.exe" setup.py install
C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cusparse64_80.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cusparse64_80.dll
The system cannot find the path specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cublas64_80.dll
The system cannot find the path specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudart64_80.dll
The system cannot find the path specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\curand64_80.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\curand64_80.dll
The system cannot find the path specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudnn64_6.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\cudnn64_6.dll*
The system cannot find the file specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>copy "C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64\nvToolsExt64_1.dll*" C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env\Lib\site-packages\torch\lib
C:\Program Files\NVIDIA Corporation\NvToolsExt\bin\x64\nvToolsExt64_1.dll
The system cannot find the path specified.
        0 file(s) copied.

(C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\_h_env) C:\ProgramData\Anaconda3\conda-bld\pytorch_1510034197347\work>if errorlevel 1 exit 1
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-build-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\cli\main_build.py", line 379, in execute
    verify=args.verify)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1776, in build_tree
    notest=notest,
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\build.py", line 1056, in build
    windows.build(m, build_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\windows.py", line 269, in build
    check_call_env(cmd, cwd=src_dir)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 676, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_build\utils.py", line 672, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmd.exe', '/c', 'bld.bat']' returned non-zero exit status 1.
```

**Comment by AdityaSoni19031997** [comment]
```
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\adity\AppData\Local\conda\conda\envs
                          C:\Users\adity\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\adity\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\adity\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False
```

**Comment by AdityaSoni19031997** [comment]
**Directory of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin**
```
07-11-2017  11:07    <DIR>          .
07-11-2017  11:07    <DIR>          ..
12-01-2017  02:08           191,032 bin2c.exe
07-11-2017  11:06    <DIR>          crt
12-01-2017  02:09        41,689,656 cublas64_80.dll
12-01-2017  02:08           346,168 cuda-memcheck.exe
12-01-2017  02:08         3,709,496 cudafe++.exe
12-01-2017  02:08         4,053,440 cudafe.exe
12-01-2017  02:09           299,064 cudart32_80.dll
12-01-2017  02:09           367,672 cudart64_80.dll
12-01-2017  02:09       145,770,944 cufft64_80.dll
12-01-2017  02:09           200,760 cufftw64_80.dll
12-01-2017  02:09         3,442,624 cuinj32_80.dll
12-01-2017  02:09         4,512,704 cuinj64_80.dll
12-01-2017  02:08         1,105,344 cuobjdump.exe
12-01-2017  02:09        48,008,248 curand64_80.dll
12-01-2017  02:09        51,923,512 cusolver64_80.dll
12-01-2017  02:09        41,833,408 cusparse64_80.dll
12-01-2017  02:08           282,168 fatbinary.exe
12-01-2017  02:08         1,212,984 gpu-library-advisor.exe
12-01-2017  02:09           197,568 nppc64_80.dll
12-01-2017  02:09       105,122,360 nppi64_80.dll
12-01-2017  02:09         9,140,792 nppial64_80.dll
12-01-2017  02:09         3,497,408 nppicc64_80.dll
12-01-2017  02:09           752,184 nppicom64_80.dll
12-01-2017  02:09         6,582,720 nppidei64_80.dll
12-01-2017  02:09        46,765,112 nppif64_80.dll
12-01-2017  02:09        20,029,376 nppig64_80.dll
12-01-2017  02:09         4,002,872 nppim64_80.dll
12-01-2017  02:09        13,585,464 nppist64_80.dll
12-01-2017  02:09           170,944 nppisu64_80.dll
12-01-2017  02:09         2,565,176 nppitc64_80.dll
12-01-2017  02:09         7,895,488 npps64_80.dll
12-01-2017  02:10           242,744 nvblas64_80.dll
12-01-2017  02:08           367,552 nvcc.exe
12-01-2017  02:09               328 nvcc.profile
12-01-2017  02:08        13,708,344 nvdisasm.exe
12-01-2017  02:09         4,145,208 nvgraph64_80.dll
12-01-2017  02:08         6,675,512 nvlink.exe
12-01-2017  02:08         4,036,032 nvprof.exe
12-01-2017  02:08           212,416 nvprune.exe
12-01-2017  02:10         9,572,864 nvrtc-builtins64_80.dll
12-01-2017  02:10        14,951,936 nvrtc64_80.dll
12-01-2017  02:10                53 nvvp.bat
12-01-2017  02:08         6,554,168 ptxas.exe
```

**Comment by AdityaSoni19031997** [comment]
I am using the ```tar file's reciepe under the user peterjc123```

**Comment by auscompgeek** [comment]
How is this relevant to Coconut?

**Comment by AdityaSoni19031997** [comment]
Sorry wrong issue..

**Comment by evhub** [comment]
@AdityaSoni19031997 This belongs in https://github.com/pytorch/pytorch/issues, not here, since this is relevant to PyTorch, not Coconut.
