### ISSUE TITLE
CoconutInternalException: out of bounds line number

### ISSUE THREAD

**Issue by creatorrr** [evhub/coconut#391]
Randomly get this error on compile, frequency seems to increase when cli is run with `-j` flag. Any ideas @evhub ?

**Comment by evhub** [comment]
@creatorrr That's definitely a bug. As a temporary fix, if you use the release version instead of the develop version it will suppress the error. For a more permanent fix, it'd be great if you could post code that replicates the error. If that's not possible, try using `--verbose` (on the latest `coconut-develop`) to get a full traceback and post that.

**Comment by dogwynn** [comment]
Using: **Coconut 1.3.1-post_dev21 [Dead Parrot]**

I have some code:

```
 >>] coconut --jupyter console
Jupyter console 5.2.0

Coconut 1.3.1-post_dev21 [Dead Parrot]


In [1]: data X:
      :     def function(self, arg):
      :         return function(self, arg)
      :
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/coconut/icoconut/root.py", line 119, in cache
    compiled = memoized_parse_sys(code)
  File "/usr/local/lib/python3.6/site-packages/coconut/icoconut/root.py", line 94, in memoized_parse_sys
    return COMPILER.header_proc(memoized_parse_block(code), header="sys", initial="none")
  File "/usr/local/lib/python3.6/site-packages/coconut/icoconut/root.py", line 87, in memoized_parse_block
    raise result
  File "/usr/local/lib/python3.6/site-packages/coconut/icoconut/root.py", line 80, in memoized_parse_block
    parsed = COMPILER.parse_block(code)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 1930, in parse_block
    return self.parse(inputstring, self.file_parser, {}, {"header": "none", "initial": "none"})
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 602, in parse
    out = self.post(parsed, **postargs)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 554, in post
    return self.apply_procs(self.postprocs, kwargs, result)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 539, in apply_procs
    inputstring = proc(inputstring, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 1079, in repl_proc
    return self.apply_procs(self.replprocs, kwargs, inputstring, log=log)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 539, in apply_procs
    inputstring = proc(inputstring, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 978, in endline_repl
    complain(err)
  File "/usr/local/lib/python3.6/site-packages/coconut/terminal.py", line 76, in complain
    raise error
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 976, in endline_repl
    line += self.ln_comment(ln)
  File "/usr/local/lib/python3.6/site-packages/coconut/compiler/compiler.py", line 933, in ln_comment
    "not in range [1, " + str(len(self.original_lines) + 1) + "]",
coconut.exceptions.CoconutInternalException: out of bounds line number: 6 (not in range [1, 5]) (you should report this at https://github.com/evhub/coconut/issues/new)
  File "<string>", line unknown
SyntaxError: out of bounds line number: 6 (not in range [1, 5]) (you should report this at https://github.com/evhub/coconut/issues/new)
```

This does not happen in the normal Coconut console, BTW:

```
>>] coconut
Coconut Interpreter:
(type 'exit()' or press Ctrl-D to end)
>>> data X:
        def function(self, arg):
            return function(self, arg)

>>> def function(x is X, arg):
        return arg

>>>
```

This is associated with another question I [posted on gitter](https://gitter.im/evhub/coconut?at=5b50b51c8578203ee7413103).

**Comment by evhub** [comment]
@creatorrr @dogwynn This should be fixed on `coconut-develop`! Just `pip install -U coconut-develop` to get the latest version.
