### ISSUE TITLE
Ipython `%%timeit` Magic is broken

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#507]
Trying to stress-test some of the parallel_map applications. Checked #168, but this is still throwing an odd problem when executed in a jupyter cell: 

```
%%timeit
(range(10000)
 |> parallel_map$(pow$(2)..>str..>.[-1])
 |>list
 |>consume
)
```

gives the following: 

```
Traceback (most recent call last):

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-54-9bb53030ee7f>", line 7, in <module>
    get_ipython().run_cell_magic('timeit', '', '(range(10000)\n |> parallel_map$(pow$(2)..>str..>.[-1])\n |>list\n |>consume\n)')  # line 1: get_ipython().run_cell_magic('timeit', '', '(range(10000)\n |> parallel_map$(pow$(2)..>str..>.[-1])\n |>list\n |>consume\n)')

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2352, in run_cell_magic
    result = fn(*args, **kwargs)

  File "</home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/decorator.py:decorator-gen-60>", line 2, in timeit

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 1124, in timeit
    code = self.shell.compile(timeit_ast, "<magic-timeit>", "exec")

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)

  File "<magic-timeit>", line 1
SyntaxError: import * only allowed at module level


```

**Comment by tbsexton** [comment]
@evhub not super familiar with the coconut internals (yet), but I believe it could be related to [this](https://stackoverflow.com/questions/21097806/import-only-allowed-at-module-level-python-3-3-using-pyscripter?rq=1), where an `import *` is being added to some kind of auto-generated code (e.g. a `__main__`, etc). Does Coconut do this, or could `timeit` be the culprit....

**Comment by evhub** [comment]
@tbsexton This should now be fixed if you `pip install -U coconut-develop`, though let me know if it's in fact working for you.

**Comment by tbsexton** [comment]
I'm still actually getting the same error. I `pip uninstall coconut` and `pip install -U coconut-develop`, followed with `coconut --jupyter notebook` and testing the same snippet above. Working in an anaconda environment, too, so there shouldn't be any strange conflicts.

**Comment by pavelbraginskiy** [comment]
The new version seems to not have made it to PyPI.

**Comment by tbsexton** [comment]
Ok, so if that's the case I tried installing directly from the develop branch using (git):

`pip install --upgrade git+https://github.com/evhub/coconut.git@develop`

That actually did change the error...now receiving this: 
```
Traceback (most recent call last):

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-62f96e14ba96>", line 6, in <module>
    get_ipython().run_cell_magic('timeit', '', '(range(10000)\n |> parallel_map$(pow$(2)..>str..>.[-1])\n |>list\n |>consume\n)')  # line 1: get_ipython().run_cell_magic('timeit', '', '(range(10000)\n |> parallel_map$(pow$(2)..>str..>.[-1])\n |>list\n |>consume\n)')

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2352, in run_cell_magic
    result = fn(*args, **kwargs)

  File "</home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/decorator.py:decorator-gen-60>", line 2, in timeit

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/site-packages/IPython/core/magics/execution.py", line 1124, in timeit
    code = self.shell.compile(timeit_ast, "<magic-timeit>", "exec")

  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.7/codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)

  File "<magic-timeit>", line 3
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Comment by evhub** [comment]
@tbsexton Okay, this time it should actually be fixed.

**Comment by tbsexton** [comment]
@evhub Trying to test this, but both above installation methods are now failing (normal `pip install coconut` still works fine. 

```
Collecting git+https://github.com/evhub/coconut.git@develop
  Cloning https://github.com/evhub/coconut.git (to revision develop) to /tmp/pip-req-build-q3cts3uo
  Running command git clone -q https://github.com/evhub/coconut.git /tmp/pip-req-build-q3cts3uo
  Running command git checkout -b develop --track origin/develop
  Switched to a new branch 'develop'
  Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Collecting cPyparsing>=2.4.0.1.0.0 (from coconut-develop==1.4.0.post0.dev35)
  Using cached https://files.pythonhosted.org/packages/cf/c5/de1d9a45e4e98ba4abf9da9232f66a8ada57e4370aaa5431d89c2a0933a6/cPyparsing-2.4.0.1.0.0.tar.gz
Requirement already satisfied, skipping upgrade: pygments>=2.3 in ./miniconda3/envs/coconut-learn/lib/python3.7/site-packages (from coconut-develop==1.4.0.post0.dev35) (2.4.0)
Requirement already satisfied, skipping upgrade: prompt_toolkit>=1 in ./miniconda3/envs/coconut-learn/lib/python3.7/site-packages (from coconut-develop==1.4.0.post0.dev35) (2.0.9)
Requirement already satisfied, skipping upgrade: wcwidth in ./miniconda3/envs/coconut-learn/lib/python3.7/site-packages (from prompt_toolkit>=1->coconut-develop==1.4.0.post0.dev35) (0.1.7)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in ./miniconda3/envs/coconut-learn/lib/python3.7/site-packages (from prompt_toolkit>=1->coconut-develop==1.4.0.post0.dev35) (1.12.0)
Building wheels for collected packages: coconut-develop, cPyparsing
  Building wheel for coconut-develop (setup.py) ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-raos8zoh/wheels/55/8b/0f/b09149437f8b9607fc74af7ff7ab3ea9821785b81ef26fa1c0
  Building wheel for cPyparsing (setup.py) ... error
  ERROR: Complete output from command /home/tbsexton/miniconda3/envs/coconut-learn/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-g86vf274/cPyparsing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-1gn4uhxq --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'cPyparsing' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  gcc -pthread -B /home/tbsexton/miniconda3/envs/coconut-learn/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/tbsexton/miniconda3/envs/coconut-learn/include/python3.7m -c cPyparsing.c -o build/temp.linux-x86_64-3.7/cPyparsing.o
  In file included from /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/syslimits.h:7,
                   from /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/limits.h:34,
                   from /home/tbsexton/miniconda3/envs/coconut-learn/include/python3.7m/Python.h:11,
                   from cPyparsing.c:16:
  /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
   #include_next <limits.h>  /* recurse down to the real one */
                 ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cPyparsing
  Running setup.py clean for cPyparsing
Successfully built coconut-develop
Failed to build cPyparsing
Installing collected packages: cPyparsing, coconut-develop
  Running setup.py install for cPyparsing ... error
    ERROR: Complete output from command /home/tbsexton/miniconda3/envs/coconut-learn/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-g86vf274/cPyparsing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_hctps8o/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'cPyparsing' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -B /home/tbsexton/miniconda3/envs/coconut-learn/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/tbsexton/miniconda3/envs/coconut-learn/include/python3.7m -c cPyparsing.c -o build/temp.linux-x86_64-3.7/cPyparsing.o
    In file included from /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/syslimits.h:7,
                     from /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/limits.h:34,
                     from /home/tbsexton/miniconda3/envs/coconut-learn/include/python3.7m/Python.h:11,
                     from cPyparsing.c:16:
    /usr/lib64/gcc/x86_64-solus-linux/8/include-fixed/limits.h:194:15: fatal error: limits.h: No such file or directory
     #include_next <limits.h>  /* recurse down to the real one */
                   ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/tbsexton/miniconda3/envs/coconut-learn/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-g86vf274/cPyparsing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_hctps8o/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-g86vf274/cPyparsing/
```

I did try installing `gcc` fresh through `eopkg` (I'm on Solus), but no luck.

**Comment by tbsexton** [comment]
Tested on my other machine (Ubuntu 19.04) and it seems to be working! Thanks!

Strange that it failed on the other though, any new/changed dependencies in the dev branch that might cause this?

**Comment by evhub** [comment]
@tbsexton The error you're looking at there is a compilation error for Coconut's `cPyparsing` extension. The dev branch has switched over to always using `cPyparsing` over the pure python `pyparsing` for performance reasons, though it also means that you'll sometimes get compilation errors. You should always be able to switch back to using the pure python `pyparsing`, though, if you follow the instructions [here](https://coconut.readthedocs.io/en/develop/DOCS.html#using-pip).
