### ISSUE TITLE
Fails to build with python2

### ISSUE THREAD

**Issue by hasufell** [evhub/coconut#527]
```
python2.7 -B setup.py config
Traceback (most recent call last):
  File "setup.py", line 53, in <module>
    readme = readme_file.read()
  File "/usr/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1147: ordinal not in range(128)
```

**Comment by hasufell** [comment]
https://github.com/evhub/coconut/commit/a24decb6011696c00981e008319ee8f08be738d2#diff-88b99bb28683bd5b7e3a204826ead112R25

This broke the parsing, it is not a normal hyphen.

**Comment by evhub** [comment]
@hasufell Should be fixed on `coconut-develop` and I'll try to get a new release out soon fixing this.

**Comment by hasufell** [comment]
As a workaround (if someone else stumbles over it), I did:

```
    iconv -c -f utf-8 -t ascii README.rst > README.tmp
    strings README.tmp > README.rst
```
