### ISSUE TITLE
Problem Connecting to coconut kernel from notebook 

### ISSUE THREAD

**Issue by tbsexton** [evhub/coconut#682]
```shell
[I 09:35:01.926 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
CONDA_PREFIX=/home/tbsexton/miniconda3/envs/coco
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/icoconut/__init__.py", line 20, in <module>
    from coconut.icoconut.root import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/icoconut/root.py", line 51, in <module>
    from coconut.compiler import Compiler
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/__init__.py", line 20, in <module>
    from coconut.compiler.compiler import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/compiler.py", line 108, in <module>
    from coconut.compiler.matching import Matcher
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/matching.py", line 44, in <module>
    from coconut.compiler.util import (
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/util.py", line 732, in <module>
    stores_loc_item = attach(Empty(), stores_loc_action)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/util.py", line 305, in attach
    return add_action(item, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/compiler/util.py", line 277, in add_action
    internal_assert(item_ref_count >= temp_grammar_item_ref_count, "add_action got item with too low ref count", (item, type(item), item_ref_count))
  File "/home/tbsexton/miniconda3/envs/coco/lib/python3.11/site-packages/coconut/terminal.py", line 118, in internal_assert
    raise error
coconut.exceptions.CoconutInternalException: add_action got item with too low ref count: (<type object at 0x55c442f9c9c0>, <class 'cPyparsing.Empty'>, 3) (you should report this at https://github.com/evhub/coconut/issues/new)
```

This comes from a new install in a fresh conda environment: 

```shell
~$ conda create -n "coco" pip
~$ conda activate coco
~$ pip install coconut[kernel] beartype
```
The kernel ends up spitting out this error and restarting 5 times. I get the little "broken chain" link symbol in my notebook.

**Comment by evhub** [comment]
I assume you're running on Python 3.11? I'm pretty sure this is a Python-3.11-specific issue. It should be fixed on `coconut-develop`, or you can just downgrade to Python 3.10.
